REFS: #98 and fixes #98 (Day-11 to 15)
rx-training/Training-Feb-2021 pull request #111
Opened 2021-02-24 06:49 UTC by paresh72

2021-02-24 07:42 UTC, MilitPanchasara reviewed
css/js links not working in Day11 assignment, plz check the same.

2021-02-24 07:48 UTC, MilitPanchasara reviewed
Day13 => Post Detail page not done, Change Password Modal remaining, Can't access drop down menu in navigation from Posts/Categories/Users pages, Styling not proper in edit profile page.

2021-02-24 07:55 UTC, MilitPanchasara reviewed
Day 15 => Apply Bootstrap in Assignment, also reset the Result when reset button is pressed.
Day 15 => In practice exercise, calculate total of numbers which are >40. Redo the logic.

2021-02-24 07:58 UTC, MilitPanchasara reviewed
Day14 => Many files are opening in new window  (for example: Day5,9,10), try to fit content in the same page.

2021-03-05 11:24 UTC, radixdt12020 requested changes
there is no department Table . Employee Table departmentid field should refer department table departmentid

2021-03-05 11:24 UTC, radixdt12020 commented on Modules/SQL/Day1/paresh gohil/Practice_exercise_1_2_3_4.sql
> +	DEPARTMENT_ID varchar(20) NOT NULL CONSTRAINT FKDEPARTMENT_ID FOREIGN KEY REFERENCES  Jobhistories(DepartmentID)
there is no department Table . Employee Table departmentid field should refer department table departmentid

2021-03-05 12:03 UTC, radixdt12020 approved these changes

2021-03-05 12:03 UTC, merged